@startuml
skinparam roundcorner 20
skinparam arrowcolor black
skinparam noteBackgroundColor PaleGoldenRod

skinparam class {
	backgroundColor LightGray
	borderColor Black
}

!definelong exception(name, type = "T")
class name <<(E,firebrick) exception>> #FCC {
	+ name(const type)
	..
	+ {abstract} const type what() const throw()
	--
	- const type
}
!enddefinelong

title Graphical User Interface Structure (GTK Wrapper)

class Application
class Widget
class Container
Widget --|> Container
class Bin
Container --|> Bin
class Window
Bin --|> Window
class Dialog
Window --|> Dialog
class AboutDialog
Dialog --|> AboutDialog
class AppChooserDialog
Dialog --|> AppChooserDialog
class ColorChooserDialog
Dialog --|> ColorChooserDialog
class FileChooserDialog
Dialog --|> FileChooserDialog
class FontChooserDialog
Dialog --|> FontChooserDialog
class FontSelectionDialog
Dialog --|> FontSelectionDialog
class MessageDialog
Dialog --|> MessageDialog

class PageSetupUnixDialog
note left: UNIX!!!
Dialog --|> PageSetupUnixDialog

class PrintUnixDialog
note left: UNIX!!!
Dialog --|> PrintUnixDialog

class RecentChooserDialog
Dialog --|> RecentChooserDialog
class ApplicationWindow
Window --|> ApplicationWindow
class Assistant
Window --|> Assistant
class OffscreenWindow
Window --|> OffscreenWindow
class Plug
Window --|> Plug
class ShortcutsWindow
Window --|> ShortcutsWindow
class ActionBar
Bin --|> ActionBar
class Alignment
Bin --|> Alignment
class ComboBox
Bin --|> ComboBox
class AppChooserButton
ComboBox --|> AppChooserButton
class ComboBoxText
ComboBox --|> ComboBoxText
class Frame
Bin --|> Frame
class AspectFrame
Frame --|> AspectFrame
class Button
Bin --|> Button
class ToggleButton
Button --|> ToggleButton
class CheckButton
ToggleButton --|> CheckButton
class RadioButton
CheckButton --|> RadioButton
class MenuButton
ToggleButton --|> MenuButton
class ColorButton
Button --|> ColorButton
class FrontButton
Button --|> FontButton
class LinkButton
Button --|> LinkButton
class LockButton
Button --|> LockButton
class ModelButton
Button --|> ModelButton
class ScaleButton
Button --|> ScaleButton
class ScaleButton
Button --|> ScaleButton
class VolumeButton
ScaleButton --|> VolumeButton
class MenuItem
Bin --|> MenuItem
class CheckMenuItem
MenuItem --|> CheckMenuItem
class RadioMenuItem
CheckMenuItem --|> RadioMenuItem
class ImageMenuItem
MenuItem --|> ImageMenuItem
class SeparatorMenuItem
MenuItem --|> SeparatorMenuItem
class TearoffMenuItem
MenuItem --|> TearoffMenuItem
class EventBox
Bin --|> EventBox
class Expander
Bin --|> Expander

class FlowBox
note left: FlowBoxChild
Bin --|> FlowBox

class HandleBox
Bin --|> HandleBox
class ListBox
note left: ListBoxRow
Bin --|> ListBox

class ToolItem
Bin --|> ToolItem
class ToolButton
ToolItem --|> ToolButton
class MenuToolButton
ToolButton --|> MenuToolButton
class ToggleToolButton
ToolButton --|> ToggleToolButton
class RadioToolButton
ToggleToolButton --|> RadioToolButton
class SeparatorToolItem
ToolItem --|> SeparatorToolItem
class Overlay
Bin --|> Overlay
class ScrolledWindow
Bin --|> ScrolledWindow
class PlacesSidebar
ScrolledWindow --|> PlacesSidebar
class Popover
Bin --|> Popover
class PopoverMenu
Popover --|> PopoverMenu
class Revealer
Bin --|> Revealer
class SearchBar
Bin --|> SearchBar
class StackSidebar
Bin --|> StackSidebar
class Viewport
Bin --|> Viewport
class Box
Container --|> Box
class AppChooserWidget
class ButtonBox
class HButtonBox
class VButtonBox
class ColorChooserWidget
class ColorSelection
class FileChooserButton
class FileChooserWidget
class FontChooserWidget
class FontSelection
class HBox
class InfoBar
class RecentChooserWidget
class ShortcutsSection
class ShortcutsGroup
class ShortcutsShortcut
class StackSwitcher
class Statusbar
class VBox
class Fixed
class Grid
class HeaderBar
class Paned
class HPaned
class VPaned
class IconView
class Layout
class MenuShell
class MenuBar
class Menu
class Notebook
class Socket
class Table
class TextView
class ToolBar
class ToolItemGroup
class ToolPalette
class TreeView
class Misc
class Label
class AccelLabel
class Arrow
class Image
class Calendar
class CellView
class DrawingArea
class Entry
class SearchEntry
class SpinButton
class GLArea
class Range
class Scale
class HScale
class VScale
class Scrollbar
class HScrollbar
class VScrollbar
class Separator
class HSeparator
class VSeparator
class HSV
class Invisible
class ProgressBar
class Spinner
class Switch
class LevelBar



@enduml
